name: Run JSON Server and Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y npm
          npm install -g json-server
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start JSON Server in the background
        run: |
          nohup json-server --watch db/db.json > json-server.log 2>&1 &
        env:
          PATH: ${{ runner.tool_cache }}/node/$(node -v)/bin:$PATH

      - name: Wait for JSON Server to be ready
        run: |
          for i in {1..30}; do
            if nc -z localhost 3000; then
              echo "JSON Server is ready."
              break
            fi
            echo "Waiting for JSON Server..."
            sleep 1
          done
          if ! nc -z localhost 3000; then
            echo "JSON Server failed to start."
            exit 1
          fi

      - name: Run Pytest
        run: pytest
        env:
          PATH: ${{ runner.tool_cache }}/node/$(node -v)/bin:$PATH

      - name: Cleanup Background Jobs
        run: |
          pkill -f "json-server --watch db/db.json" || true
